# Generated by Django 3.0.8 on 2020-07-27 10:23

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200727_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='document',
            field=models.FileField(upload_to='upload_content_doc/', validators=[users.validators.ValidateFileExtension]),
        ),
    ]
