# Generated by Django 3.0.8 on 2020-07-20 18:10

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200720_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15, validators=[users.validators.MinimumLengthValidator, users.validators.UppercaseValidator, users.validators.LowercaseValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(max_length=6, validators=[users.validators.OnlyNumberValidator]),
        ),
    ]
